export const PlayerData = [
    {
        "id":1,
        "name":"Web3gamed",
        "points":2,
        "percent":2.04,
        "amount":0.01,
        "image":"",
        "color":"red"
    },
    {
        "id":2,
        "name":"harrypotter36_5345",
        "points":9,
        "percent":40.04,
        "amount":0.2,
        "image":"",
        "color":"blue"
    },
    {
        "id":3,
        "name":"treboomin",
        "points":20,
        "percent":20.41,
        "amount":0.1,
        "image":"",
        "color":"orange"
    },
    {
        "id":4,
        "name":"c4a4e7",
        "points":4,
        "percent":4.08,
        "amount":0.02,
        "image":"",
        "color":"green"
    },
]